# Generated by Django 4.2.15 on 2024-08-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image_url',
            new_name='image',
        ),
    ]
